name: Python package

on: [push]

jobs:
  stylecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install Dependencies
        run: |
          pip install ".[test]"
          mypy html_to_django || true
          mypy --install-types --non-interactive
      - name: Stylecheck
        run: |
          mypy --strict html_to_django
          pycodestyle --max-line-length 120 html_to_django
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: pip install ".[test]"
      - name: Test on Python ${{ matrix.python-version }}
        run: python -m unittest discover tests --verbose
